dbus-update-activation-environment --all &
xrandr --setprovideroutputsource modesetting NVIDIA-0 &
xrandr --auto &
feh --bg-scale --randomize /home/hetav/Pictures/Wallpapers/* &
picom --daemon &
. ~/.scripts/xsetloop.sh &
clipmenud &
exec dbus-launch --sh-syntax --exit-with-session dwm

#wallpics/* & 
#~/Pictures/Wallpapers/* &
